### ISSUE TITLE
Relicense for GPL 2 compability?

### ISSUE THREAD

**Issue by spth** [rurban/libu8ident#10]
The currently used license is a free copyleft license, compatible with GPL 3. However, I am not sure if the incompability with GPL 2 is intentional.
If GPL 2 compability is wanted, a copyleft option would be to dual-license under "GPL2 or later" and the current license.

**Comment by rurban** [comment]
No it's not intentional. But why GPL-2? Who is using that besides the Linux kernel

**Comment by spth** [comment]
SDCC currently is licensed under "GPLv2 or later" (unless the treedec library was installed at configure time, then it is "GPLv3 or later"). Looking at statistics, GPLv2 is apparently still as common as GPLv3, e.g.
https://www.statista.com/statistics/1245643/worldwide-leading-open-source-licenses/
Also, since you already have a GPLv3-compatible license, making it GPLv2-compatible seemed like a small change to propose (as opposed to proposing a non-copyleft license, such as MIT/Expat/BSD/zlib) and thus more likely to be accepted.

Since I am an SDCC author, use of the library in SDCC (once it has found its way into GNU/Linux and BSD distributions) would be a use case for me. Or maybe at that time this library might actually be a motivation to migrate SDCC to "GPLv3 or later", who knows.

**Comment by rurban** [comment]
Ah, sdcc! fine, I'll add more licenses for the next release. still working on faster lookups.

**Comment by stefan-hdt** [comment]
If you are talking about incompatibility between GPL-2.0-only and Apache-2.0, this is discussed and not a clear issue. The Free Software Foundation has the opinion that it incompatible while the Apache Software Foundation has no problem here (see https://www.apache.org/licenses/GPL-compatibility.html).

**Comment by rurban** [comment]
Done
